### ISSUE TITLE
Support for the route subdomain enhancement

### ISSUE THREAD

**Issue by vinzent** [cert-manager/openshift-routes#10]
Upcoming OpenShift releases  (maybe 4.11)  support to specify `.spec.subdomain` in OpenShift Route resources instead of `.spec.host`. The `.spec.subdomain` value will be extended by the Routers domain. `.spec.host` will not be filled for such routes. The hostname(s) can be found in `.status.ingress[].host`. Multiple OpenShift Routers can expose a single Route  - so multiple host values can exist.

Enhancement docs: https://github.com/openshift/enhancements/blob/master/enhancements/ingress/route-subdomain.md

**Comment by jacksgt** [comment]
Hi, 
I'm interested in picking this up. Is anyone else already working on this or has a design?

For reference, this is the commit that introduces the change: https://github.com/openshift/router/commit/6f730c7cae966f0ed8def50c81d1bf10fe9eb77b

And here are the release notes for 4.11: https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-routes-spec-subdomain-field

> Previously, you could not specify the subdomain of a route, and the spec.host field was required to set the host name. You can now specify the spec.subdomain field and omit the spec.host field of a route. The router deployment that exposes the route will use the spec.subdomain value to determine the host name.

**Comment by maelvls** [comment]
@jacksgt I would gladly review your PR if you wish to contribute this feature.

**Comment by jacksgt** [comment]
> @jacksgt I would gladly review your PR if you wish to contribute this feature.

Thanks! I'll probably look into it next week. In the meantime, could you review https://github.com/cert-manager/openshift-routes/pull/22 ?
