### ISSUE TITLE
Feature: Support for ECC certs

### ISSUE THREAD

**Issue by seandilda** [cert-manager/openshift-routes#15]
https://cert-manager.io/docs/faq/#is-ecc-elliptic-curve-cryptography-supported indicates ECC keys can be used if the `privateKey` is properly set in the `Certificate` object.

It would be great if we could have access to do this through openshift-routes.

This may be related to #4.

**Comment by maelvls** [comment]
Hi! @vinny-sabatini added support for ECDSA keys. The feature is available since [v0.3.0](https://github.com/cert-manager/openshift-routes/releases/tag/v0.3.0).

I'll close this issue; feel free to re-open if you feel something is missing.
