### ISSUE TITLE
possible interop issue with new cert-manager operator version v1.10.0

### ISSUE THREAD

**Issue by nate-duke** [cert-manager/openshift-routes#16]
We're using this plugin to configure our Routes in our OKD4 clusters and started getting a cert error (incorrect subject name) talking to the cert-manager service.

```
E1103 16:12:16.053541       1 controller.go:326] cert-manager-openshift-routes/controller-manager "msg"="Reconciler error" "error"="Internal error occurred: failed calling webhook \"mutate.webhooks.cert-manager.io\": failed to call webhook: Post \"https://cert-manager-webhook-service.openshift-operators.svc:443/mutate?timeout=10s\": x509: certificate is valid for cert-manager-webhook, cert-manager-webhook.openshift-operators, cert-manager-webhook.openshift-operators.svc, not cert-manager-webhook-service.openshift-operators.svc" "controller"="route" "controllerGroup"="route.openshift.io" "controllerKind"="Route" "name"="whoami-external" "namespace"="nbc9-stuff" "reconcileID"="d2ba6bb6-cc08-4373-bd0e-633e0da4ed61" "route"={"name":"whoami-external","namespace":"nbc9-stuff"} 
```
I don't see anything related in the [v1.10.0 changelog](https://github.com/cert-manager/cert-manager/releases/tag/v1.10.0) so i'm not sure where it came from.

The services defined do seem to be a little odd as well (20h ago was when we pulled in the v1.10.0 update to the cert-manager operator):
```
❯ kubectl get svc
NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
cert-manager                   ClusterIP   10.129.203.158   <none>        9402/TCP   62d
cert-manager-webhook           ClusterIP   10.129.152.47    <none>        443/TCP    62d
cert-manager-webhook-service   ClusterIP   10.129.211.108   <none>        443/TCP    20h
```
I'm not sure if this is a cert-manager operator bug, a cert-manager/openshift-routes bug or just an "us" bug.

**Comment by nate-duke** [comment]
thanks a bunch @wallrj!

**Comment by jacksgt** [comment]
Hi there,
if I understand correctly this issue should be closed - or why was it re-opened?

**Comment by nate-duke** [comment]
@jacksgt  It was reopened because at the time the issue was not resolved. i.e. the cert-manager with the fix was unreleased.

Does seem to be released now though

/
