### ISSUE TITLE
Namespace is hardcoded

### ISSUE THREAD

**Issue by tomerleib** [cert-manager/openshift-routes#17]
Hi,

I have modified the cert-manager-route to match the namespace where my cert-manager was installed but the application failed to work and create the certs for routes.
When I checked the logs of the pod I saw that it kept searching for  namespace `cert-manager`, although it is running in a different namespace.

```bash
E1115 17:39:54.701737 1 leaderelection.go:334] error initially creating leader election record: namespaces "cert-manager" not found
I1115 17:39:54.701755 1 leaderelection.go:253] failed to acquire lease cert-manager/cert-manager-openshift-routes
I1115 17:39:56.786822 1 shared_informer.go:285] caches populated
```

**Comment by reavessm** [comment]
I'm getting this same error.  Is there a workaround?
