### ISSUE TITLE
Feature: Force renew certificate

### ISSUE THREAD

**Issue by hawksight** [cert-manager/openshift-routes#3]
Currently there doesn't look to be a way to renew a certificate attached to the route.

Use case is to test out the renewal process in cluster, ensure the whole pipeline works as intended and there are no issues with the CA / Issuer at renewal time.

Something similar to `cmctl renew <cert>` would be helpful.

Maybe an annotation, which if read, generates a new certificate request and then is removed? (Could be a terrible idea)

**Comment by andjos** [comment]
If you remove the certificate part of the route, it will trigger an renew.

**Comment by inteon** [comment]
@andjos Thank you for explaining.
@hawksight Please re-open in case any additional actions are needed here.
