### ISSUE TITLE
How to populate certificate metadata i.e. subject details e.g. OU, Organization etc

### ISSUE THREAD

**Issue by ajaykanse** [cert-manager/openshift-routes#35]
HI,

We are testing this add-on in OpenShift with OpenShift-cert-manager operator. The installation worked fine and the initial testing with specified annotations in README worked as expected. However we are looking for annotations that can be used for certificate metadata such as subject - Organization Unit, Organization, locality, state, country etc. Basically we are hoping to have annotations available for all the fields that certificate resource provides from configuration standpoint.
Currently all these fields are coming as blank. Please let us know if we have annotation available or is there any plan for implementing those.

Thanks

**Comment by ctrought** [comment]
Both of the below are requirements

1. #29 needs to be merged in this repo which adds support for subject annotations, I've been a little slow getting back to the maintainers but I am going to update the PR shortly!
2. Coincidentally I was also the one who submitted a similar PR for supporting subject fields on ingresses in cert-manager, those are supported as of cert-manager v1.12.0. After the #29 is merged, you would probably want to be running cert-manager v1.12.0 or higher to align with the version used in openshift-routes but it might work with an older version too. OpenShift cert-manager-operator is only at v1.11.4 as it trails upstream by at least 1 minor version.
