### ISSUE TITLE
Feature: Allow specification of privateKey.rotationPolicy

### ISSUE THREAD

**Issue by hawksight** [cert-manager/openshift-routes#4]
Currently there isn't an option to specify the private key rotation policy. TPP requires this to be Always (by default) and might cause issues at renewal time if the same private key is reused by the controller.

Maybe something like:

```yaml
cert-manager.io/private-key-rotation-policy: "Always"
```

**Comment by ctrought** [comment]
I'll be submitting a PR soon for adding support for some other annotations we require, but regarding rotation policy it looks to me like as of today it does always generate a new private key during each renewal.

https://github.com/cert-manager/openshift-routes/blob/main/internal/controller/sync.go#L75

**Comment by maelvls** [comment]
@ctrought is correct, the private key is always rotated by default. @hawksight Do you still think there is need, for example to set it to `Never`?

@vinzent Thanks to @snorwin's efforts, it is now possible to configure the key size since v0.4.0! ✨

**Comment by hawksight** [comment]
I wasn't aware of exactly how this project worked before, so assuming that each time this controller makes a certificate request that it generates a new private key, I think that is a good default and this can be closed.

I can't image why you wouldn't want that, so I see no reason to set it to `Never`. But now I have said that, I almost guarantee someones will need that.. maybe we just close this and wait for someone to create that hypothetical issue, and deal with it then.
