### ISSUE TITLE
release needed to make README.md instructions valid.

### ISSUE THREAD

**Issue by nate-duke** [cert-manager/openshift-routes#7]
The manifest deployment of the cert-manager-openshift-routes mentioned in the README.md pulls from the latest release on Github which includes a security context that won't be allowed without anyuid set for the service account. Since this was removed in 857bb1481d9703d1d629a8eadb8d36113b2b92b1 i'm assuming that a run of the release process would include that commit which makes the instructions in the README.md work.

Cheers for putting this together btw, this is great.

**Comment by jakexks** [comment]
Release v0.1.2 is in progress 🎉
