### ISSUE TITLE
Future of Static Manifest?

### ISSUE THREAD

**Issue by maelvls** [cert-manager/openshift-routes#73]
With the goal of making openshift-routes a little more maintainable (as in: making release processes more consistent across cert-manager projects), Tim changed the release process of openshift-routes in #60. Up to v0.5.0, the static manifest was available in the GitHub Release assets, and it was possible to do:

```bash
oc apply -f https://github.com/cert-manager/openshift-routes/releases/download/v0.5.0/cert-manager-openshift-routes.yaml
```

This manifest was generated using [hack/generate-static-manifest.sh](https://github.com/cert-manager/openshift-routes/blob/v0.5.0/hack/generate-static-manifest.sh) and used the source of truth [`static/cert-manager-openshift-routes.yaml`](https://github.com/cert-manager/openshift-routes/blob/v0.5.0/deploy/static/cert-manager-openshift-routes.yaml) instead of the Helm chart. Having two sources of truth isn't great, so we would like to change that.

I see two options going forward (v0.6.0 and beyond):

1. ~Low effort: add instructions to the README to explain how to generate the same static manifests using a Helm command; but you will no longer be able to `oc install -f https://...`~
2. Some effort: generate and push static manifest from the Helm chart to the GitHub Release assets (same as we already do on the cert-manager project) → we decided to go with this approach.

For to let you know @vinny-sabatini @jacksgt @mbu147 @gaohoward @ctrought @hawksight

**Comment by maelvls** [comment]
I've described the changes between the old static manifest (v0.5.0 and below) and the new one that would be generated using `--set omitHelmLabels=true`: https://github.com/cert-manager/openshift-routes/pull/74.

**Comment by maelvls** [comment]
I talked to Tim this morning. We decided to keep shipping the static manifest.

Plan:

- I'll add `--set omitHelmLabels=true` as part of v0.6.0: #74
- I'll release v0.6.0 in a few weeks and I'll manually upload the static manifest.
- After releasing, we will automate the upload of this static manifest.

**Comment by inteon** [comment]
Slight update: we haven't automated uploading the static manifest, instead we updated the instructions to show how to Helm template a static manifest. This allows static manifest users to also use the Helm configuration options if desired.
